### ISSUE TITLE
cannot load such file -- [...]/humanize-1.2.0/lib/words

### ISSUE THREAD

**Issue by jerefrer** [radar/humanize#12]
I just updated humanize to use it in my project and it crashed, saying it cannot locate the `words.rb` file.

When I looked into the gem directory on my machine the `words.rb` file was indeed missing. But it's present on the repo.

Do you have an idea why ? Might `words` be a reserved word somehow ?

It is working when setting `gem 'humanize', github: 'radar/humanize'` in my `Gemfile`.

**Comment by radar** [comment]
This file wasn't included in the gemspecs `files` list. I've now amended this in 1e77c88 and have released 1.2.1 to fix this issue.

**Comment by jerefrer** [comment]
Oh my bad, thanks !
