### ISSUE TITLE
Needs Configuration to Remove "and" Separating Large Numbers for Check Amount Fields

### ISSUE THREAD

**Issue by vmoore61** [radar/humanize#14]
A nifty feature for this gem would be a configuration that allows you to choose whether or not you want "and" between large numbers (e.g. "Nine hundred Ninety Nine Thousand" vs "Nine Hundred and Ninety Nine Thousand"). 

When writing a check, it is generally good practice to only include "and" between the whole dollar amount and the fraction representing cents at the end so that it is clear where the dollars end and the cents begin, and this gem would be absolutely perfect for this use if not for the and's included in the output strings.

**Comment by vmoore61** [comment]
Closing, as after further investigation shows that you can just set the and config line in each locale to a blank string.

**Comment by radar** [comment]
That's a relatively new feature too :) Glad you were able to solve it.

**Comment by egallup02360** [comment]
Sorry to reopen such an old issue, but according to the code below this doesn't seem possible to override anymore. Am I missing something?

```ruby
def conjunction(parts, use_and)
  return '' if parts.empty?

  use_and ? ' and' : ','
end
```
