### ISSUE TITLE
Incompatible with Ruby 1.9 but no required_ruby_version in gemspec

### ISSUE THREAD

**Issue by cgriego** [radar/humanize#16]
Starting with v1.2.0, humanize fails on Ruby versions prior to 2.0 because of non ASCII characters added to files like `lots.rb` without encoding comments. But the gemspec doesn't state a required Ruby version, so this issue isn't found until trying to load the code that Rubygems has already installed.

```
humanize-1.2.2/lib/lots.rb:3: syntax error, unexpected $end, expecting ']'
...'nonillion', 'nonilliard', 'décillion', 'décilliard', 'und...
...                               ^
```

**Comment by radar** [comment]
Might be possible to fix this with the special encoding comment line on top of that particular file.

Could you please submit a patch for that?
