### ISSUE TITLE
consider including money/currency?

### ISSUE THREAD

**Issue by dan-ding** [radar/humanize#19]
Similar to decimal/float but instead of "x point y", it'd be "x [currency] and y [currency]" (for English at least)

0.42.humanize(decimals_as: :currency) # => "forty-two cents"
1.42.humanize(decimals_as: :currency) # => "one dollar and forty-two cents"

What do you think?

**Comment by radar** [comment]
I would prefer it to be a differently named method, like humanize_currency. I like the idea and look forward to seeing your patch.

**Comment by dan-ding** [comment]
ok! will get back shortly!

**Comment by watkins** [comment]
@dan-ding Did you ever end up adding this feature?

**Comment by dan-ding** [comment]
I haven't forgotten!

**Comment by radar** [comment]
Still haven’t forgotten?

**Comment by radar** [comment]
Closing as because I haven't heard anything back. I prefer not to leave feature request issues open. Please submit a PR if you would like this feature.
