### ISSUE TITLE
consider changing the name?

### ISSUE THREAD

**Issue by yairEO** [radar/humanize#21]
"humanize" is already an established well-known github project.. might confuse people. suggestions:

    4.wordify
    4.toWords

Also would be cool to have a reverse method to convert the string of words back to a Number

**Comment by radar** [comment]
You neglected to include a link to this "established well-known project"

**Comment by radar** [comment]
Also, no

**Comment by radar** [comment]
Perhaps you meant https://github.com/Humanizr/Humanizer, which is a .Net project. I won't change the name of a Ruby library because it conflicts with a .Net one. That would just be ridiculous.

**Comment by yairEO** [comment]
https://github.com/HubSpot/humanize

I've been knowing it for years now. maybe 5... it might not have many stars, but it is well known project

**Comment by radar** [comment]
This project you point at is a JS project. My project is a Ruby project. Projects across different ecosystems are allowed to have the same name.

You have no case.
