### ISSUE TITLE
Float numbers with zero

### ISSUE THREAD

**Issue by galetahub** [radar/humanize#24]
Hi,

First of all thanks for grete gem
We have problem with next example
```
0.042.humanize(decimals_as: :number)
# "zero point forty-two"
```
It take's string "042".to_i and then convert it to words.
I think in this case we must detect zero

**Comment by radar** [comment]
Thanks for the bug report. Happy to look at pull requests and sign off on them myself. Looking forward to seeing what solution you come up with.

**Comment by styd** [comment]
Hi, @radar.
With my PR merged, this issue should be closed, right?

**Comment by radar** [comment]
Yup, that's right.
