### ISSUE TITLE
Float conversions break after 5 decimal places.

### ISSUE THREAD

**Issue by styd** [radar/humanize#31]
Repost the following comment:
https://github.com/radar/humanize/pull/3#commitcomment-6039210
as issue report.

```ruby
0.0003.humanize
#=> "zero point zero zero zero three"
0.00003.humanize
#=> "zero point zero zero zero zero five"
# expected: "zero point zero zero zero zero three"
0.000003.humanize
#=> "zero point zero zero zero zero six"
# expected: "zero point zero zero zero zero zero three"
```
Update:
Btw, this issue only occurs when the number is `0.0000XXX` or `-0.0000XXX`.

**Comment by radar** [comment]
Probably need special casing to handle scientific notation in Ruby:

`0.00000042` => "4.2e-07"

**Comment by styd** [comment]
@radar, you're right. I guess that's the source of the problem.
I think I've come up with a little bit of a hack to convert the floats to string that is not a scientific notation.
What do you think about this?:
```ruby
num = 0.000000032452345
digits, exp = num.to_s.split("e-")
"%.#{digits[/\d+$/].length + exp.to_i}f" % num
#=> "0.000000032452345"
```

This works for other floats too:
```ruby
num = 0.032452345
digits, exp = num.to_s.split("e-")
"%.#{digits[/\d+$/].length + exp.to_i}f" % num
#=> "0.032452345"
```
If this looks good, I will send the PR.

**Comment by styd** [comment]
Hi, @radar. I thought I just send you the PR so you can easily review and test it. 😬
