### ISSUE TITLE
Number 10**18 and above are breaking in Indonesian locale

### ISSUE THREAD

**Issue by styd** [radar/humanize#35]
Currently:
```ruby
1_000_000_000_000_000_000.humanize(:locale => :id)
# => NoMethodError: undefined method `+' for nil:NilClass
```
If any of you Indonesians knows the name of these unnamed scales: 

**['', 'ribu', 'juta', 'miliar', 'triliun', 'kuadriliun', 10<sup>18</sup>, 10<sup>21</sup>, 10<sup>24</sup>, 10<sup>27</sup>, 'kuintiliun', 'desiliun', 10<sup>36</sup>, .. ]**,

please let us know in the comments or send us a PR.

As you can see, I've found the names of **10<sup>30</sup>** and **10<sup>33</sup>**. But it supposed to be contiguous so that it wouldn't break.

**Comment by radar** [comment]
Wouldn’t kuintillion == quintillion, and kaudrillion == quadrillion? So kaudrillion should be directly before kuintillion? In English, quad being 4 and quin being 5. Isn’t it the same in Indonesian too?

**Comment by styd** [comment]
I thought so too. But, according to:
- [http://kateglo.com/?mod=dictionary&action=view&phrase=kuintiliun](http://kateglo.com/?mod=dictionary&action=view&phrase=kuintiliun), and
- [https://kbbi.web.id/kuintiliun](https://kbbi.web.id/kuintiliun)

`kuintiliun` is `sepuluh pangkat tiga puluh (di Amerika Serikat: sepuluh pangkat lima belas)`.
In English that would be `ten to the power of thirty (in the United States of America: ten to the power of fifteen)`

These websites (_kateglo.com_ and _kbbi.web.id_) use the official dictionary data from _Pusat Bahasa Kementerian Pendidikan dan Kebudayaan_ (the Ministry of Education and Culture's Center of Indonesian language). I believe _kateglo.com_ is the most updated one. Many Indonesian translators used either these or the printed dictionary to check the standard spelling and the most accurate meaning of an Indonesian word. I know this because I was [a translator](https://www.felicitrans.com/about/) (although not very good at it). I still am actually, but now only occasionally.

As for `desiliun`, the definition is `satuan bilangan besar (di atas satu juta) yang dilambangkan dengan 33 nol pada sistem Amerika atau dengan 60 nol pada sistem Inggris`. In English: `a unit of large number (above one million) which is denoted by 33 zeroes in American system or by 60 zeroes in British system`. I assume Indonesian would follow the American system because it usually is unless otherwise specified as in the case of `kuintiliun`.

**Comment by styd** [comment]
I've asked one of the experts of Indonesian language [in twitter](https://twitter.com/_setyadi/status/932512116346515457) about this and still waiting for his reply.
[He](https://en.wikipedia.org/wiki/Ivan_Lanin) is the main creator of _kateglo.com_.

**Comment by styd** [comment]
This issue has been opened for long. I assume nobody knows the answers either or maybe they haven't been defined. So, I'm closing this issue.
Anyone is welcome to reraise it if needed.
