### ISSUE TITLE
Decimals not being humanized for BigDecimal numbers

### ISSUE THREAD

**Issue by skuark** [radar/humanize#44]
It seems there is a problem generating the humanized version of BigDecimal decimal part.

```
-> % irb
irb(main):001:0> require 'humanize'
=> true
irb(main):002:0> 123.45.humanize
=> "one hundred and twenty-three point four five"
irb(main):003:0> BigDecimal.new("123.45")
=> 0.12345e3
irb(main):004:0> BigDecimal.new("123.45").humanize
=> "one hundred and twenty-three"
```

**Comment by styd** [comment]
I haven't checked it yet. But, if you know how to fix it, pull request is very much appreciated.

**Comment by styd** [comment]
For the record, I was the one who added BigDecimal.

**Comment by styd** [comment]
You're welcome, @skuark. Thanks for reporting the issue.
