### ISSUE TITLE
PT local suport

### ISSUE THREAD

**Issue by nelsonmfinda** [radar/humanize#45]
I am currently developing a system, and one of the feature is converting numbers into text. Then I would like to contribute to the project by adding support for PT (Portuguese).

**Comment by nelsonmfinda** [comment]
With the help of the other contributors, I wanted to understand what steps you should take to do the translation. I know it's not enough to just use a translator or something similar. Thank you!

**Comment by radar** [comment]
How did you generate the cache?

**Comment by styd** [comment]
Are you asking me or @nelsonmfinda, @radar?

**Comment by styd** [comment]
Since there has to be a pattern in number 0 to 999. You can generate most of it by looping through number the number in text.

**Comment by nelsonmfinda** [comment]
> Hi, @nelsonmfinda. You can follow what I did [here](https://github.com/radar/humanize/commit/a8f2ec7d9739148ebba953624eb4b4e80b2f01aa).

Thanks :+1:
