### ISSUE TITLE
ru locale support

### ISSUE THREAD

**Issue by arharovets** [radar/humanize#48]
Hi guys,

I'm adding support for Russian, and I've run into a couple of issues:
1. A lot of language-specific rules. For example:
``` bash
1000.humanize
# => "одна тысяча"

2000.humanize
# => "две тысячи"

5000.humanize
# => "пять тысяч"
```
I can search the output string for a specific combination of words, and then replace it with the right ones but this solution will be relatively slow since it requires an iteration through a pretty big list of combinations. 
Maybe there's a better way?

2. When I tried to replace words in the output string, I have faced an `invalid byte sequence in UTF-8` error.

Thank you!

**Comment by radar** [comment]
Yes, replacing one word at a time is how to do it.

Can you show us a branch that shows the UTF8 error please? Hard to debug it without codeZ

**Comment by arharovets** [comment]
@radar Thank you for the answer!

Sorry, false alarm. Just recompiled rubies and the error has disappeared.
I need a couple of days now to polish specific rules.

**Comment by arharovets** [comment]
Decimals support is still an issue due to its complex nature in native Russian.
For example,
```bash
# It is a hell lotta more rules

123.221.humanize
# => "сто двадцать три целых, двести двадцать одна тысячная"

10231.00146.humanize
# => "десять тысяч двести тридцать одна целая, сто сорок шесть десятитысячных"
```
Nevertheless, basic support for the language is added so I'm closing this issue. I will continue to work on it.
