### ISSUE TITLE
Error in /locales/constants/de.rb

### ISSUE THREAD

**Issue by howa** [radar/humanize#51]
POINT = 'Punkt'.freeze 
should read 
POINT = 'Komma'.freeze
quick-fix / monkey patch: In your Ruby Code use
Humanize::De::POINT = 'Komma'

**Comment by radar** [comment]
Please submit a patch to fix this.

**Comment by styd** [comment]
Googling a bit, I found that German also uses "," to separate decimals just like Indonesian. So @howa's must be true.

**Comment by radar** [comment]
Fixed by #52.

**Comment by radar** [comment]
humanize 2.1.1 has been released which fixes this problem.
