### ISSUE TITLE
Gem based on Humanize

### ISSUE THREAD

**Issue by Sbfrr** [radar/humanize#6]
Hi,

I forked your gem to build https://github.com/nexkap/humanize .
I added features such as the possibility to add different languages (english and french are available for now) and specify rounding options. The focus was not on the performance (my version is slower than yours) since I'm using this lib to generate documents in a delayed job but more on additional features.

It's still a first draft and will be updated in the coming days . However I was wondering if you'd be interested or not in a pull request  since the code now differs a lot from your initial project . If you don't, please feel free to ask me to change the name of the project. You'll still have your name in the contributors and thanks list anyway.

Let me know.

**Comment by radar** [comment]
Hi @Sbfrr, I'm happy for you to fork the project and modify it as you wish. I think I will want to be keeping my code simple. I'm happy to also allow you to continue using the name.
