### ISSUE TITLE
Duplicate in SUB_ONE_GROUPING for RU locale

### ISSUE THREAD

**Issue by miralita** [radar/humanize#60]
Duplicate value "семьдесят восемь"

**Comment by miralita** [comment]
Another bug in SUB_ONE_GROUPING: unneeded comma in ', шестьдесят один'

**Comment by miralita** [comment]
... and missed 'двести семьдесят шесть' between 'двести семьдесят семь' and 'двести семьдесят восемь'

**Comment by radar** [comment]
Patches welcome.

**Comment by radar** [comment]
Fixed by #61
