### ISSUE TITLE
How can I contribute a Spanish (es) translation?

### ISSUE THREAD

**Issue by fercreek** [radar/humanize#62]
Hi! I want to add es locales, there's a documentation to contribute?

**Comment by radar** [comment]
There is no documentation for contributing. It is a very small library, and so I would recommend looking at the existing translations. You could also look through past PRs like #43 and #49.

**Comment by fercreek** [comment]
Thanks @radar ! Im'm doing the spanish translate 👍 
There's a way of use this gem using console?

Last thing, can you add this a label for hacktoberfest? https://hacktoberfest.digitalocean.com/details

**Comment by radar** [comment]
You can run `bin/console` inside this gem to run an `irb` console to test out this gem.

I've added the label for Hacktoberfest now.

**Comment by fercreek** [comment]
Nice! I made my PR https://github.com/radar/humanize/pull/63 @radar :)
