### ISSUE TITLE
Discussion: Shouldn't we Use I18n.locale by default?

### ISSUE THREAD

**Issue by K1N5L4Y3R** [radar/humanize#76]
Maybe I'm missing something here, but I think that it would be useful if `#humanize` would use current locale (`I18n.locale`) by default when available.

One could still change to a different locale on a per-call basis by doing something like:

```ruby
# the current way
n.humanize(locale: :es)

# or
I18n.with_locale(:es) do
  n.humanize
end
```

, but I think that if your app/project has I18n, you'll probably want to use the current locale for humanizing numbers most of the times.

If it makes sense, I'd be happy to find some time to submit a PR with a proposal in the next couple of weeks.

**Comment by radar** [comment]
This library has no dependency on i18n and never will.

**Comment by K1N5L4Y3R** [comment]
I understand. Thanks.
